disabled_rules: # Default Rules에서 비활성화할 규칙
    # 라인 뒤에 공백이 없어야 합니다. https://realm.github.io/SwiftLint/trailing_whitespace.html
    - trailing_whitespace
    # 강제 캐스팅은 피해야합니다. https://realm.github.io/SwiftLint/force_cast.html
    - force_cast
    # 강제 언래핑은 피해야합니다. https://realm.github.io/SwiftLint/force_unwrapping.html
    - force_unwrapping
    # https://realm.github.io/SwiftLint/identifier_name.html
    - identifier_name
    # https://realm.github.io/SwiftLint/type_name.html
    - type_name
    # https://realm.github.io/SwiftLint/vertical_whitespace.html
    - vertical_whitespace
opt_in_rules: # 기본적으로는 비활성화 되어있지만, 내가 활성화 하고 싶은 규칙
    # .count==0 보다는 .isEmpty를 사용하는 것이 좋습니다. https://realm.github.io/SwiftLint/empty_count.html
    - empty_count
    # 빈 String 문자열과 비교하는 것 보다는 .isEmpty를 사용하는 것이 좋습니다. https://realm.github.io/SwiftLint/empty_string.html
    - empty_string
included:
  - orrnrr
  - orrnrrTests
  - orrnrrUITests
excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
    - Carthage
    - Pods

