# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:

  # Lint
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          DIFF_BASE: ${{ github.base_ref }}
      - name: GitHub Action for SwiftLint (Different working directory)
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          WORKING_DIRECTORY: Source
          
      - name: send slack message
        uses: 8398a7/action-slack@v3
        with:
          mention: 'Lint error'
          if_mention: failure
          status: ${{ job.status }}
          fields: workflow,job,commit,message,ref,author,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()


  # Build
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Xcode
      run: |
        xcodebuild clean test -project orrnrr/orrnrr.xcodeproj \
        -scheme orrnrr \
        -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest'
        
    - name: send slack message
      uses: 8398a7/action-slack@v3
      with:
        mention: 'build fail'
        if_mention: failure
        status: ${{ job.status }}
        fields: workflow,job,commit,message,ref,author,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
        

